### ISSUE TITLE
`onInterrupted` should be curried

### ISSUE THREAD

**Issue by sledorze** [mikearnaldi/matechs-effect#102]
This also applies to other combinators.
We may need to 'stuff (more) the monad' (eventually new TC)
Also consider Fluent

**Comment by mikearnaldi** [comment]
Additionally we should also expose an es6 build to allow tree shaking, this will involve writing also some kind of import-path-rewrite similar to the one used for fp-ts-contrib

**Comment by mikearnaldi** [comment]
done in #138
