### ISSUE TITLE
Discuss Representation of Cancellability

### ISSUE THREAD

**Issue by rzeigler** [mikearnaldi/matechs-effect#106]
For reference, the current signature of an Async is
`FunctionN<[FunctionN<[Either<E, A>], void>], Lazy<void>`
which for simplicity I shall reproduce in HM as
`(Either e a -> Unit) -> (Unit -> Unit)` 
for less noise.

The return is a callback that invokes cancellation.
This is unsatisfying for several reasons. 
Chief among them is that the uninterruptible combinator exists to bracket effects that shouldn't be cancelled for semantic reasons or resource safety.
However, there is at least a class of effects (see node fs module operations) that are inherently uninterruptible.
Forcing users to be aware of the nuances of cancelation is likely error prone.

Additionally, this model fails to capture cases where cancelation itself might fail or take some time to complete.
In these cases we are potentially allowing the dispatch loop to advance before an effect is truly complete which has implications for semantics.

I was recently doing some research and I came across the cancelation signature for purescript-aff which has an interesting signature. 
The cancellation signature in Aff (given at https://github.com/purescript-contrib/purescript-aff/blob/master/src/Effect/Aff/Compat.purs#L21) is 
`newtype EffectFnCanceler = EffectFnCanceler (EffectFn3 Error (EffectFnCb Error) (EffectFnCb Unit) Unit)`
Which translates roughly to `Error -> (Error -> Unit) -> (Unit -> Unit) -> Unit`
I.e. a canceler receives the interrupt error and a callback for cancelation succeeded and cancelation failed.

Something similar would improve the expression power of Async. 
Delayed interruption is expressable via the callbacks and inherent uninterruptibility can be expressed by providing a cancel function that declines to invoke callbacks.
In this case, the driver would resume via normal completion, check the interruption flag as it does at event boundaries and take action there. 
No need for remembering uninterruptible when wrapping node fs for instance.

This may need to be a breaking change to the API if only because of the semantics change might be confusing otherwise.
While it might be possible to maintain backwards compatibility by making the current Async delegate to the enhanced async such that cancellation is assumed synchronous and safe this is probably not the best strategy.
Certainly the type of the Effect union would change which is breaking anyway so might as well go all the way.
The impact is probably most commonly felt at integration anyway, user code mostly wouldn't need to change barring assumption that it makes around how fast cancelation completes.

**Comment by mikearnaldi** [comment]
on the topic @sledorze did some research on interrupt semanthics maybe he can share it here

**Comment by mikearnaldi** [comment]
@rzeigler digging in this I am puzzled, the caller of interrupt will provide ideally onSuccess & onError but what happens in case we need to cancel multiple things and we have multiple failures? shall we call multiple times the onError? shall we mangle in some ways the errors?

**Comment by rzeigler** [comment]
I think the representation of errors should be a free monoid with the error at the head. In most cases this would be the interruption with any errors that occur during finalization appended. I started working on this but ran into some compilation issues with the fold machinery around Effect/EffectIO and wasn't able tor resolve it.

**Comment by mikearnaldi** [comment]
@rzeigler I've made some progress on https://github.com/mikearnaldi/matechs-effect/pull/132 but I don't get why it's not playing with streams, also very unsure about onInterrupt

**Comment by mikearnaldi** [comment]
something extremely weird, if I add a log around https://github.com/mikearnaldi/matechs-effect/pull/132/files#diff-912e2798d34c7257ac233e23e859f7fbR1325 then the switchLatest completes but with a wrong result

**Comment by mikearnaldi** [comment]
found the issue, was a missing cb in effect/never, I think it's more or less ready for review #132

**Comment by mikearnaldi** [comment]
Covered by https://github.com/mikearnaldi/matechs-effect/pull/134 we can take care of lifting contextswitch in a different PR
